name: Comment on failed linting

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Comment on pull request
        uses: actions/github-script@v6
        with:
          script: |
            const failedJobs = '${{ github.event.workflow_run.jobs.lint.outputs }}';
            let message = `Linter is failing on your pull request. Please enable pre-commit hooks (info under this link: ...) \n\n`;
            if (failedJobs.includes('isort')) {
              message += `For the issue with isort, you can run:\n\n\`isort .\`\n\nAnd then commit the changes:\n\n\`git commit -am "ran isort"\`\n\`git push\`\n`;
            }
            if (failedJobs.includes('black')) {
              message += `For the issue with black, you can run:\n\n\`black .\`\n\nAnd then commit the changes:\n\n\`git commit -am "ran black"\`\n\`git push\`\n`;
            }
            const { context, GitHub } = require("@actions/github");
            const octokit = new GitHub(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message,
            });
